FROM node:0.12.6-slim

RUN apt-get -y update
RUN apt-get -y install git python-software-properties build-essential

ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/

WORKDIR /opt/app
ADD . /opt/app
RUN rm -rf node_modules
RUN npm install
CMD npm test

